// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ControleEmprestimo.Data.Models
{
    [Keyless]
    public partial class ListarLivroClienteEmprestimo
    {
        [Required]
        [Column("cliCPF")]
        [StringLength(50)]
        public string CliCpf { get; set; }
        [Required]
        [Column("cliNome")]
        [StringLength(100)]
        public string CliNome { get; set; }
        [Required]
        [Column("livroNome")]
        [StringLength(100)]
        public string LivroNome { get; set; }
        [Column("id")]
        public int Id { get; set; }
        public int? LceidLivro { get; set; }
        public int? LceidCliente { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LcedataEmprestimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LcedataEntrega { get; set; }
        public bool? LceEntregue { get; set; }
    }
}